name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: 
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🚑️ Hot Fixes"
    labels:
      - "hotfix"
  - title: "⚡️ Improve performance"
    labels: 
      - "perf"
      - "performance"
  - title: "📝 Add or update documentation"
    labels:
      - "docs"
  - title: "🔒️ Security"
    labels:
      - "security"
  - title: "👷 CI/CD"
    labels:
      - "ci"
      - "cd"
  - title: "♻️ Refactor"
    labels:
      - "refactor"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

autolabeler:
  - label: 'feat'
    branch:
      - '/feat\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'perf'
    branch:
      - '/perf\/.+/'
      - '/performance\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
  - label: 'ci'
    branch:
      - '/ci\/.+/'
  - label: 'cd'
    branch:
      - '/ci\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'

    
template: |
  ## Changes

  $CHANGES
